#!/usr/bin/env bash
set -e

while getopts e:*: option
do
	case "${option}"
	in
	e) ENVIRONMENT=${OPTARG};;
	*) # Handles unassigned arguments 
	esac
done

# shellcheck disable=SC1091
source config -e "$ENVIRONMENT"

mkdir -p "packages"
zip -r -j  "packages/node_health_check.zip" "lambda/nodehealthcheck/"
aws s3 cp "packages/node_health_check.zip" "s3://$US_EAST_1_LAMBDA_BUCKET/$APPLICATION/$ENVIRONMENT/"

zip -r -j "packages/replication.zip" "lambda/replication/"
aws s3 cp "packages/replication.zip" "s3://$PRIMARY_LAMBDA_BUCKET/$APPLICATION/$ENVIRONMENT/"

zip -r -j "packages/deletion.zip" "lambda/deletion/"
aws s3 cp "packages/deletion.zip" "s3://$PRIMARY_LAMBDA_BUCKET/$APPLICATION/$ENVIRONMENT/"
